setting:
  seed: 20000812
  os_environ:
    CUDA_VISIBLE_DEVICES: 0   # ,1,2,3
    MASTER_ADDR: 127.0.0.1
    MASTER_PORT: 45848
    WORLD_SIZE: 1
    NODE_RANK: 0
    #      WANDB_MODE: offline
  wandb_config:
    project: ProteinGym
    name: ProtLigand-Cross-Attention-With-Generated-Ligands

  out_path: output/ProteinGym/newest_protligand_cross_attention.tsv
  # out_path: output/ProteinGym/SaProt_650M_AF2.tsv

  dataset_dir: LMDB/ProteinGym/substitutions

model:
  model_py_path: saprot/saprot_foldseek_mutation_model
  kwargs:
    foldseek_path: bin/foldseek
    config_path: weights/PLMs/SaProt_650M_AF2
    load_pretrained: True
    plddt_threshold: 70

  from_checkpoint: weights/Pretrain/final_prot_ligand_model.pt

dataset:
  dataset_py_path: mutation_zeroshot_dataset
  dataloader_kwargs:
    batch_size: 4
    num_workers: 1
  kwargs: {}

Trainer:
  log_every_n_steps: 1
  devices: 1
  accelerator: gpu
  num_nodes: 1
  strategy:
    find_unused_parameters: False
  logger: True
