setting:
  seed: 20000812
  os_environ:
    WANDB_API_KEY: ~
    WANDB_RUN_ID: ~
    CUDA_VISIBLE_DEVICES: 0,1,2,3
    MASTER_ADDR: 127.0.0.1
    MASTER_PORT: 38448
    WORLD_SIZE: 1
    NODE_RANK: 0
#      WANDB_MODE: offline
  wandb_config:
    project: PreTraining
    name: Ligand-Generator-With-Decoder

model:
#    Which model to use
  model_py_path: saprot/saprot_generator_model
  kwargs:
#    Arguments to initialize the specific class
    config_path: weights/PLMs/SaProt_650M_AF2
    load_pretrained: True

#    Arguments to initialize the basic class AbstractModel
  lr_scheduler_kwargs:
    last_epoch: -1
    init_lr: 6.0e-5   # 2.0e-5
#    max_lr: 6.0e-5
#    final_lr: 1.0e-5
#    warmup_steps: 10000
#    start_decay_after_n_steps: 30000
#    end_decay_after_n_steps: 60000
    # Weather to use this scheduler or not
    on_use: False   # True

  optimizer_kwargs:
    betas: [0.9, 0.98]
    weight_decay: 0.01

  # from_checkpoint: weights/Pretrain/ligand_generator_model_with_decoder_new.pt
  save_path: weights/Pretrain/ligand_generator_model_with_decoder_big.pt
  load_prev_scheduler: false
  save_weights_only: false


dataset:
#    Arguments to initialize the basic class LMDBDataset
  dataset_py_path: saprot/generator_foldseek_dataset
  dataloader_kwargs:
    batch_size: 1
    num_workers: 4

  train_lmdb: LMDB/PDBBind/train
  valid_lmdb: LMDB/PDBBind/valid
  test_lmdb: LMDB/PDBBind/valid

#    Arguments to initialize the specific class
  kwargs:
    tokenizer: weights/PLMs/SaProt_650M_AF2
    max_length: 1024
    mask_ratio: 0.15


#  Arguments to initialize Pytorch Lightning Trainer
Trainer:
  max_epochs: 100
  max_steps: 1000000
  min_steps: 1000000
  log_every_n_steps: 1
  accelerator: gpu
  devices: 4
  accumulate_grad_batches: 4
  num_nodes: 1
  strategy:
    find_unused_parameters: True
  logger: True
  enable_checkpointing: false
  num_sanity_val_steps: 0
  val_check_interval: 1.0
  precision: 16
  limit_val_batches: 1.0
  limit_test_batches: 1.0
